# -*- coding: utf-8 -*-
"""lulc_2016-ml-mask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/jeevanmp99/3eb018582df0301f949f60132d5a7b98/lulc_2016-ml-mask.ipynb
"""

!pip install rasterio geopandas scikit-learn matplotlib numpy

import geopandas as gpd
import rasterio
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from rasterio.plot import show
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

# File paths
landsat_path = '/content/drive/MyDrive/2016lulc/composite16_cliped.tif'
train_shp_path = '/content/drive/MyDrive/2016lulc/TRAIN_2016_3.shp'
dem_path = '/content/drive/MyDrive/2016lulc/dem_resamp'
slope_path = '/content/drive/MyDrive/2016lulc/slope_resamp'

# Load training samples
samples = gpd.read_file(train_shp_path)
print("Training Samples Loaded:", samples.head())

# Load Landsat image
with rasterio.open(landsat_path) as src:
    landsat = src.read()
    landsat_meta = src.meta
    landsat_transform = src.transform
    landsat_crs = src.crs
    print("Landsat Image Loaded. Shape:", landsat.shape)

# Load DEM and Slope
with rasterio.open(dem_path) as dem_src:
    dem = dem_src.read(1)
    dem_meta = dem_src.meta
    print("DEM Loaded. Shape:", dem.shape)

with rasterio.open(slope_path) as slope_src:
    slope = slope_src.read(1)
    slope_meta = slope_src.meta
    print("Slope Loaded. Shape:", slope.shape)

# Stack Landsat, DEM, and Slope
stacked_image = np.vstack([landsat, dem[np.newaxis, :, :], slope[np.newaxis, :, :]])
print("Stacked Image Shape:", stacked_image.shape)

# Extract training data
train_data = []
for index, row in samples.iterrows():
    row_x, row_y = row.geometry.x, row.geometry.y
    px, py = ~landsat_transform * (row_x, row_y)
    px, py = int(px), int(py)
    if 0 <= px < landsat.shape[2] and 0 <= py < landsat.shape[1]:
        features = stacked_image[:, py, px]
        label = row['Class']  # Assuming class column exists in shapefile
        train_data.append(list(features) + [label])

# Convert to DataFrame
columns = [f'Band_{i+1}' for i in range(landsat.shape[0])] + ['DEM', 'Slope', 'Class']
df = pd.DataFrame(train_data, columns=columns)
print("Training Data Extracted:", df.head())

# Split into features and labels
X = df.drop(columns=['Class'])
y = df['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train Random Forest Model
clf = RandomForestClassifier(n_estimators=800, random_state=42)
clf.fit(X_train, y_train)

# Evaluate Model
y_pred = clf.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

# Predict LULC Map
reshaped_data = stacked_image.reshape(stacked_image.shape[0], -1).T
predicted_lulc = clf.predict(reshaped_data)
predicted_lulc = predicted_lulc.reshape(landsat.shape[1:])

# Save Classified Image
output_path = '/content/drive/MyDrive/2016lulc/LULC_2016'
with rasterio.open(output_path, 'w', **landsat_meta) as dst:
    dst.write(predicted_lulc.astype(rasterio.uint8), 1)

print("LULC Classification Completed. Output saved at:", output_path)

# Visualize Results
plt.figure(figsize=(10, 6))
plt.imshow(predicted_lulc, cmap='jet')
plt.colorbar()
plt.title("LULC Classification")
plt.show()